import React, { createContext, useContext, useState, useEffect } from 'react';

const SettingsContext = createContext();

const translations = {
    'English (US)': {
        'Overview': 'Overview',
        'Lockers': 'Lockers',
        'Residents': 'Residents',
        'Events': 'Events',
        'Settings': 'Settings',
        'Admin Panel': 'Admin Panel',
        'Logout': 'Logout',
        'Total Deliveries': 'Total Deliveries',
        'Revenue': 'Revenue',
        'Efficiency': 'Efficiency',
        'Issues': 'Issues',
        'Occupancy Trends': 'Occupancy Trends',
        'This Week': 'This Week',
        'Last Week': 'Last Week',
        'Recent Activity': 'Recent Activity',
        'Add Unit': 'Add Unit',
        'Refresh Status': 'Refresh Status',
        'Ready for use': 'Ready for use',
        'Occupied': 'Occupied',
        'Open': 'Open',
        'Reset': 'Reset',
        'Locker ID': 'Locker ID',
        'Resident Directory': 'Resident Directory',
        'Add Resident': 'Add Resident',
        'User': 'User',
        'Apartment': 'Apartment',
        'Actions': 'Actions',
        'Delete': 'Delete',
        'Edit': 'Edit',
        'Full Name': 'Full Name',
        'Email': 'Email',
        'Apartment ID': 'Apartment ID',
        'Cancel': 'Cancel',
        'Save Changes': 'Save Changes',
        'System Events': 'System Events',
        'All Types': 'All Types',
        'Date Range': 'Date Range',
        'Time Range': 'Time Range',
        'From': 'From',
        'To': 'To',
        'Clear Dates': 'Clear Dates',
        'Clear Times': 'Clear Times',
        'System Name': 'System Name',
        'Organization / Building Name': 'Organization / Building Name',
        'Timezone': 'Timezone',
        'Language': 'Language',
        'Locker Management': 'Locker Management',
        'Install New Locker': 'Install New Locker',
        'Loading Dashboard...': 'Loading Dashboard...',
        'Confirm Action': 'Confirm Action',
        'Confirm Override': 'Confirm Override',
        'General settings saved!': 'General settings saved!',
        'Locker configuration saved!': 'Locker configuration saved!',
        'Security settings saved!': 'Security settings saved!',
        'Notification settings saved!': 'Notification settings saved!',
        'Hardware settings saved!': 'Hardware settings saved!',
        'User management settings saved!': 'User management settings saved!',
        'Appearance settings saved!': 'Appearance settings saved!',
        'General': 'General',
        'Locker Config': 'Locker Config',
        'Security': 'Security',
        'Notifications': 'Notifications',
        'Hardware': 'Hardware',
        'User Mgmt': 'User Mgmt',
        'Appearance': 'Appearance',
        'Locker Configuration': 'Locker Configuration',
        'Auto Lock Delay (seconds)': 'Auto Lock Delay (seconds)',
        'Unlock Duration (seconds)': 'Unlock Duration (seconds)',
        'Door Open Timeout (seconds)': 'Door Open Timeout (seconds)',
        'Enable Auto-lock': 'Enable Auto-lock',
        'Automatically lock the door after the delay period': 'Automatically lock the door after the delay period',
        'Security Settings': 'Security Settings',
        'OTP Expiry Time (minutes)': 'OTP Expiry Time (minutes)',
        'Maximum Failed Attempts': 'Maximum Failed Attempts',
        'Session Timeout (minutes)': 'Session Timeout (minutes)',
        'Enable Two Factor Authentication': 'Enable Two Factor Authentication',
        'Require an extra code for administrative logins': 'Require an extra code for administrative logins',
        'Notification Settings': 'Notification Settings',
        'Email Notifications': 'Email Notifications',
        'Receive system updates via email': 'Receive system updates via email',
        'SMS Notifications': 'SMS Notifications',
        'Receive urgent alerts via SMS': 'Receive urgent alerts via SMS',
        'Door Left Open Alerts': 'Door Left Open Alerts',
        'Notify if a locker door remains open too long': 'Notify if a locker door remains open too long',
        'Failed Access Alerts': 'Failed Access Alerts',
        'Notify after suspicious failed entry attempts': 'Notify after suspicious failed entry attempts',
        'Hardware Settings': 'Hardware Settings',
        'Device Status': 'Device Status',
        'Last heartbeat': 'Last heartbeat',
        'Device Name': 'Device Name',
        'Device IP Address': 'Device IP Address',
        'Test Connection': 'Test Connection',
        'Restart Device': 'Restart Device',
        'Simulate System Alert': 'Simulate System Alert',
        'Connected': 'Connected',
        'Testing connection to': 'Testing connection to',
        'Are you sure you want to restart the hardware controller?': 'Are you sure you want to restart the hardware controller?',
        'Restart command sent.': 'Restart command sent.',
        'System Alert simulated! Check the Events Log.': 'System Alert simulated! Check the Events Log.',
        'User Management Settings': 'User Management Settings',
        'Allow Resident Self Registration': 'Allow Resident Self Registration',
        'Residents can create their own accounts via the user app': 'Residents can create their own accounts via the user app',
        'Maximum Lockers per Resident': 'Maximum Lockers per Resident',
        'Resident Inactivity Timeout (days)': 'Resident Inactivity Timeout (days)',
        'Appearance Settings': 'Appearance Settings',
        'Theme': 'Theme',
        'Applied': 'Applied',
        'Light': 'Light',
        'Dark': 'Dark',
        'Theme is applied instantly — no save required.': 'Theme is applied instantly — no save required.',
        'Primary Color': 'Primary Color',
        'Organization Logo': 'Organization Logo',
        'Change Logo': 'Change Logo',
        'PNG, JPG or SVG. Max 2MB.': 'PNG, JPG or SVG. Max 2MB.',
        'Description': 'Description',
        'Type': 'Type',
        'Locker': 'Locker',
        '2 minutes ago': '2 minutes ago',
        'Search...': 'Search...',
        'Admin User': 'Admin User',
        'Super Admin': 'Super Admin',
        'Super User': 'Super User',
        'View All': 'View All',
        'Loading...': 'Loading...',
        'No recent activity': 'No recent activity',
        'Showing last 10 system events': 'Showing last 10 system events',
        'No events found.': 'No events found.',
        'DELIVERY': 'Delivery',
        'PICKUP': 'Pickup',
        'CLOSE': 'Close',
        'ADMIN_OVERRIDE': 'Admin Override',
        'SYSTEM_ALERT': 'System Alert',
        'EVENT': 'Event',
        'Delivery': 'Delivery',
        'Pickup': 'Pickup',
        'Verify Email': 'Verify Email',
        '6-Digit OTP': '6-Digit OTP',
        'Verify & Continue': 'Verify & Continue',
        'Update Resident': 'Update Resident',
        'Complete Registration': 'Complete Registration',
        'Update Registration': 'Update Registration',
        'Didn\'t get a code? Resend': 'Didn\'t get a code? Resend',
        'No Activity': 'No Activity',
        'Verify Gmail': 'Verify Gmail',
        'No residents found.': 'No residents found.',
        'Admin Override Warning': 'Admin Override Warning',
        'You are about to manually': 'You are about to manually',
        'locker': 'locker',
        'This action will be logged in the system audit trail.': 'This action will be logged in the system audit trail.',
        'force open': 'force open',
        'reset': 'reset',
        'Must be unique across the system.': 'Must be unique across the system.',
        'desc_admin_reset': 'Locker {lockerId} manually reset by administrator',
        'desc_delivery': 'New package for {owner} in Locker {lockerId}',
        'desc_pickup': 'Package collected by resident of Apt {apt}',
        'desc_admin_open': 'Locker door opened by administrator override',
        'desc_close': 'Locker door closed and secured',
        'desc_alert': 'System Alert: Irregular activity detected on unit {lockerId}',
        'No description provided': 'No description provided',
        'Revenue per Pickup ($)': 'Revenue per Pickup ($)',
        'Revenue Settings': 'Revenue Settings',
        'Amount earned per successful package pickup': 'Amount earned per successful package pickup',
        'Download Logo': 'Download Logo'
    },
    'Malayalam': {
        'Overview': 'അവലോകനം',
        'Lockers': 'ലോക്കറുകൾ',
        'Residents': 'താമസക്കാർ',
        'Events': 'ഇവന്റുകൾ',
        'Settings': 'ക്രമീകരണങ്ങൾ',
        'Admin Panel': 'അഡ്മിൻ പാനൽ',
        'Logout': 'പുറത്തു കടക്കുക',
        'Total Deliveries': 'ആകെ ഡെലിവറികൾ',
        'Revenue': 'വരുമാനം',
        'Efficiency': 'കാര്യക്ഷമത',
        'Issues': 'പ്രശ്നങ്ങൾ',
        'Occupancy Trends': 'ഉപയോഗ പ്രവണതകൾ',
        'This Week': 'ഈ ആഴ്ച',
        'Last Week': 'കഴിഞ്ഞ ആഴ്ച',
        'Recent Activity': 'സമീപകാല പ്രവർത്തനങ്ങൾ',
        'Add Unit': 'യൂണിറ്റ് ചേർക്കുക',
        'Refresh Status': 'നില പുതുക്കുക',
        'Ready for use': 'ഉപയോഗത്തിന് തയ്യാറാണ്',
        'Occupied': 'ഉപയോഗത്തിലാണ്',
        'Open': 'തുറക്കുക',
        'Reset': 'റീസെറ്റ് ചെയ്യുക',
        'Locker ID': 'ലോക്കർ ഐഡി',
        'Resident Directory': 'താമസക്കാരുടെ പട്ടിക',
        'Add Resident': 'താമസക്കാരനെ ചേർക്കുക',
        'User': 'ഉപയോക്താവ്',
        'Apartment': 'അപ്പാർട്ട്മെന്റ്',
        'Actions': 'നടപടികൾ',
        'Delete': 'ഡിലീറ്റ്',
        'Edit': 'എഡിറ്റ്',
        'Full Name': 'പൂർണ്ണനാമം',
        'Email': 'ഇമെയിൽ',
        'Apartment ID': 'അപ്പാർട്ട്മെന്റ് ഐഡി',
        'Cancel': 'റദ്ദാക്കുക',
        'Save Changes': 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
        'System Events': 'സിസ്റ്റം ഇവന്റുകൾ',
        'All Types': 'എല്ലാ തരങ്ങളും',
        'Date Range': 'തിയതി പരിധി',
        'Time Range': 'സമയ പരിധി',
        'From': 'മുതൽ',
        'To': 'വരെ',
        'Clear Dates': 'തിയതികൾ ഒഴിവാക്കുക',
        'Clear Times': 'സമയങ്ങൾ ഒഴിവാക്കുക',
        'System Name': 'സിസ്റ്റം പേര്',
        'Organization / Building Name': 'സ്ഥാപനം / കെട്ടിടത്തിന്റെ പേര്',
        'Timezone': 'സമയമേഖല',
        'Language': 'ഭാഷ',
        'Locker Management': 'ലോക്കർ മാനേജ്മെന്റ്',
        'Install New Locker': 'പുതിയ ലോക്കർ സ്ഥാപിക്കുക',
        'Loading Dashboard...': 'ഡാഷ്‌ബോർഡ് ലോഡ് ചെയ്യുന്നു...',
        'Confirm Action': 'ഈ നടപടി സ്ഥിരീകരിക്കുക',
        'Confirm Override': 'ഓവർറൈഡ് സ്ഥിരീകരിക്കുക',
        'General settings saved!': 'സാധാരണ ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'Locker configuration saved!': 'ലോക്കർ ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'Security settings saved!': 'സുരക്ഷാ ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'Notification settings saved!': 'അറിയിപ്പ് ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'Hardware settings saved!': 'ഹാർഡ്‌വെയർ ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'User management settings saved!': 'ഉപയോക്തൃ മാനേജ്‌മെന്റ് ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'Appearance settings saved!': 'കാഴ്ചാ ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു!',
        'General': 'സാധാരണ',
        'Locker Config': 'ലോക്കർ ക്രമീകരണം',
        'Security': 'സുരക്ഷ',
        'Notifications': 'അറിയിപ്പുകൾ',
        'Hardware': 'ഹാർഡ്‌വെയർ',
        'User Mgmt': 'ഉപയോക്തൃ മാനേജ്‌മെന്റ്',
        'Appearance': 'കാഴ്ച',
        'Locker Configuration': 'ലോക്കർ ക്രមീകരണം',
        'Auto Lock Delay (seconds)': 'ഓട്ടോ ലോക്ക് സമയം (സെക്കൻഡ്)',
        'Unlock Duration (seconds)': 'തുറന്നു പിടിക്കുന്ന സമയം (സെക്കൻഡ്)',
        'Door Open Timeout (seconds)': 'ഡോർ ഓപ്പൺ ടൈംഔട്ട് (സെക്കൻഡ്)',
        'Enable Auto-lock': 'ഓട്ടോ ലോക്ക് പ്രവർത്തിപ്പിക്കുക',
        'Automatically lock the door after the delay period': 'നിശ്ചിത സമയത്തിന് ശേഷം ഡോർ തനിയെ ലോക്ക് ചെയ്യുക',
        'Security Settings': 'സുരക്ഷാ ക്രമീകരണങ്ങൾ',
        'OTP Expiry Time (minutes)': 'ഒടിപി കാലാവധി (മിനിറ്റ്)',
        'Maximum Failed Attempts': 'പരമാവധി പരാജയപ്പെട്ട ശ്രമങ്ങൾ',
        'Session Timeout (minutes)': 'സെഷൻ കാലാവധി (മിനിറ്റ്)',
        'Enable Two Factor Authentication': 'ടു ഫാക്ടർ ഓതന്റിക്കേഷൻ പ്രവർത്തിപ്പിക്കുക',
        'Require an extra code for administrative logins': 'അഡ്മിൻ ലോഗിന് അധിക സുരക്ഷാ കോഡ് ആവശ്യപ്പെടുക',
        'Notification Settings': 'അറിയിപ്പ് ക്രമീകരണങ്ങൾ',
        'Email Notifications': 'ഇമെയിൽ അറിയിപ്പുകൾ',
        'Receive system updates via email': 'സിസ്റ്റം മാറ്റങ്ങൾ ഇമെയിൽ വഴി അറിയുക',
        'SMS Notifications': 'എസ്എംഎസ് അറിയിപ്പുകൾ',
        'Receive urgent alerts via SMS': 'അടിയന്തര അറിയിപ്പുകൾ എസ്എംഎസ് വഴി അറിയുക',
        'Door Left Open Alerts': 'ഡോർ തുറന്നിരുന്നാൽ അറിയിക്കുക',
        'Notify if a locker door remains open too long': 'ലോക്കർ ഡോർ കൂടുതൽ സമയം തുറന്നിരുന്നാൽ അറിയിപ്പ് നൽകുക',
        'Failed Access Alerts': 'പരാജയപ്പെട്ട പ്രവേശന അറിയിപ്പുകൾ',
        'Notify after suspicious failed entry attempts': 'അസ്വാഭാവികമായ പരാജയപ്പെട്ട ശ്രമങ്ങൾ നടന്നാൽ അറിയിക്കുക',
        'Hardware Settings': 'ഹാർഡ്‌വെയർ ക്രമീകരണങ്ങൾ',
        'Device Status': 'ഉപകരണത്തിന്റെ നില',
        'Last heartbeat': 'അവസാന പ്രതികരണം',
        'Device Name': 'ഉപകരണത്തിന്റെ പേര്',
        'Device IP Address': 'ഉപകരണത്തിന്റെ ഐപി വിലാസം',
        'Test Connection': 'കണക്ഷൻ പരിശോധിക്കുക',
        'Restart Device': 'ഉപകരണം റീസ്റ്റാർട്ട് ചെയ്യുക',
        'Simulate System Alert': 'അലേർട്ട് പരിശോധിക്കുക',
        'Connected': 'ബന്ധിപ്പിച്ചിരിക്കുന്നു',
        'Testing connection to': 'കണക്ഷൻ പരിശോധിക്കുന്നു',
        'Are you sure you want to restart the hardware controller?': 'നിങ്ങൾക്ക് ഹാർഡ്‌വെയർ കൺട്രോളർ റീസ്റ്റാർട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
        'Restart command sent.': 'റീസ്റ്റാർട്ട് നിർദ്ദേശം അയച്ചു.',
        'System Alert simulated! Check the Events Log.': 'അലേർട്ട് പരിശോധിച്ചു! ഇവന്റ് ലോഗ് നോക്കുക.',
        'User Management Settings': 'ഉപയോക്തൃ മാനേജ്‌മെന്റ് ക്രമീകരണങ്ങൾ',
        'Allow Resident Self Registration': 'താമസക്കാർക്ക് തനിയെ രജിസ്റ്റർ ചെയ്യാൻ അനുവദിക്കുക',
        'Residents can create their own accounts via the user app': 'താമസക്കാർക്ക് ആപ്പ് വഴി സ്വന്തമായി അക്കൗണ്ട് തുടങ്ങാം',
        'Maximum Lockers per Resident': 'ഒരാൾക്ക് എടുക്കാവുന്ന പരമാവധി ലോക്കറുകൾ',
        'Resident Inactivity Timeout (days)': 'ഉപയോഗിക്കാതിരിക്കാവുന്ന കാലാവധി (ദിവസം)',
        'Appearance Settings': 'കാഴ്ചാ ക്രമീകരണങ്ങൾ',
        'Theme': 'തീം',
        'Applied': 'മാറ്റം വരുത്തി',
        'Light': 'ലൈറ്റ്',
        'Dark': 'ഡാർക്ക്',
        'Theme is applied instantly — no save required.': 'തീം ഉടൻ മാറ്റം വരുത്തുന്നു - സേവ് ചെയ്യേണ്ടതില്ല.',
        'Primary Color': 'പ്രധാന നിറം',
        'Organization Logo': 'സ്ഥാപനത്തിന്റെ ലോഗോ',
        'Change Logo': 'ലോഗോ മാറ്റുക',
        'PNG, JPG or SVG. Max 2MB.': 'PNG, JPG അല്ലെങ്കിൽ SVG. പരമാവധി 2MB.',
        'Description': 'വിവരണം',
        'Type': 'തരം',
        'Locker': 'ലോക്കർ',
        '2 minutes ago': '2 മിനിറ്റ് മുൻപ്',
        'Search...': 'തിരയുക...',
        'Admin User': 'അഡ്മിൻ യൂസർ',
        'Super Admin': 'സൂപ്പർ അഡ്മിൻ',
        'Super User': 'സൂപ്പർ യൂസർ',
        'View All': 'എല്ലാം കാണുക',
        'Loading...': 'ലോഡ് ചെയ്യുന്നു...',
        'No recent activity': 'സമീപകാല പ്രവർത്തനങ്ങളൊന്നുമില്ല',
        'Showing last 10 system events': 'അവസാന 10 സിസ്റ്റം ഇവന്റുകൾ കാണിക്കുന്നു',
        'No events found.': 'ഇവന്റുകളൊന്നും കണ്ടെത്തിയില്ല.',
        'DELIVERY': 'ഡെലിവറി',
        'PICKUP': 'പിക്ക്അപ്പ്',
        'CLOSE': 'അടയ്ക്കുക',
        'ADMIN_OVERRIDE': 'അഡ്മിൻ ഓവർറൈഡ്',
        'SYSTEM_ALERT': 'സിസ്റ്റം അലേർട്ട്',
        'EVENT': 'ഇവന്റ്',
        'Delivery': 'ഡെലിവറി',
        'Pickup': 'പിക്ക്അപ്പ്',
        'Verify Email': 'ഇമെയിൽ പരിശോധിക്കുക',
        '6-Digit OTP': '6-അക്ക OTP',
        'Verify & Continue': 'പരിശോധിച്ചു തുടരുക',
        'Update Resident': 'റസിഡന്റ് അപ്‌ഡേറ്റ് ചെയ്യുക',
        'Complete Registration': 'രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക',
        'Update Registration': 'രജിസ്ട്രേഷൻ അപ്‌ഡേറ്റ് ചെയ്യുക',
        'Didn\'t get a code? Resend': 'കോഡ് ലഭിച്ചില്ലേ? വീണ്ടും അയക്കുക',
        'No Activity': 'പ്രവർത്തനങ്ങളില്ല',
        'Verify Gmail': 'Gmail പരിശോധിക്കുക',
        'No residents found.': 'താമസക്കാരെയൊന്നും കണ്ടെത്തിയില്ല.',
        'Admin Override Warning': 'അഡ്മിൻ ഓവർറൈഡ് മുന്നറിയിപ്പ്',
        'You are about to manually': 'നിങ്ങൾ സ്വയം ചെയ്യാൻ പോകുകയാണ്',
        'locker': 'ലോക്കർ',
        'This action will be logged in the system audit trail.': 'ഈ പ്രവർത്തനം സിസ്റ്റം ഓഡിറ്റ് ട്രയലിൽ രേഖപ്പെടുത്തും.',
        'force open': 'ബലമായി തുറക്കുക',
        'reset': 'റീസെറ്റ് ചെയ്യുക',
        'Must be unique across the system.': 'സിസ്റ്റത്തിൽ ഉടനീളം അദ്വിതീയമായിരിക്കണം.',
        'desc_admin_reset': 'ലോക്കർ {lockerId} അഡ്മിനിസ്ട്രേറ്റർ സ്വമേധയാ റീസെറ്റ് ചെയ്തു',
        'desc_delivery': 'ലോക്കർ {lockerId}-ൽ {owner}-ന് പുതിയ പാക്കേജ് എത്തി',
        'desc_pickup': 'അപ്പാർട്ട്മെന്റ് {apt}-ലെ താമസക്കാരൻ പാക്കേജ് സ്വീകരിച്ചു',
        'desc_admin_open': 'അഡ്മിനിസ്ട്രേറ്റർ ഓവർറൈഡ് വഴി ലോക്കർ വാതിൽ തുറന്നു',
        'desc_close': 'ലോക്കർ വാതിൽ അടച്ചു സുരക്ഷിതമാക്കി',
        'desc_alert': 'സിസ്റ്റം അലേർട്ട്: യൂണിറ്റ് {lockerId}-ൽ അസാധാരണമായ പ്രവർത്തനം കണ്ടെത്തി',
        'No description provided': 'വിവരണം നൽകിയിട്ടില്ല',
        'Revenue per Pickup ($)': 'ഓരോ പിക്കപ്പിനും ലഭിക്കുന്ന വരുമാനം ($)',
        'Revenue Settings': 'വരുമാന ക്രമീകരണങ്ങൾ',
        'Amount earned per successful package pickup': 'ഓരോ വിജയകരമായ പാക്കേജ് പിക്കപ്പിനും ലഭിക്കുന്ന തുക',
        'Download Logo': 'ലോഗോ ഡൗൺലോഡ് ചെയ്യുക'
    },
    'Hindi': {
        'Overview': 'अवलोकन',
        'Lockers': 'लॉकर्स',
        'Residents': 'निवासी',
        'Events': 'ईवेंट्स',
        'Settings': 'सेटिंग्स',
        'Admin Panel': 'एडमिन पैनल',
        'Logout': 'लॉगआउट',
        'Total Deliveries': 'कुल डेलिवरी',
        'Revenue': 'राजस्व',
        'Efficiency': 'दक्षता',
        'Issues': 'समस्याएँ',
        'Occupancy Trends': 'ऑक्यूपेंसी रुझान',
        'This Week': 'इस सप्ताह',
        'Last Week': 'पिछला सप्ताह',
        'Recent Activity': 'हालकी गतिविधि',
        'Add Unit': 'यूनिट जोड़ें',
        'Refresh Status': 'स्थिति ताज़ा करें',
        'Ready for use': 'उपयोग के लिए तैयार',
        'Occupied': 'व्यस्त',
        'Open': 'खोलें',
        'Reset': 'रीसेट करें',
        'Locker ID': 'लॉकर आईडी',
        'Resident Directory': 'निवासी निर्देशिका',
        'Add Resident': 'निवासी जोड़ें',
        'User': 'उपयोगकर्ता',
        'Apartment': 'अपार्टमेंट',
        'Actions': 'क्रियाएं',
        'Delete': 'हटाएं',
        'Edit': 'संपादित करें',
        'Full Name': 'पूरा नाम',
        'Email': 'ईमेल',
        'Apartment ID': 'अपार्टमेंट आईडी',
        'Cancel': 'रद्द करें',
        'Save Changes': 'परिवर्तन सहेजें',
        'System Events': 'सिस्टम ईवेंट्स',
        'All Types': 'सभी प्रकार',
        'Date Range': 'तिथि सीमा',
        'Time Range': 'समय सीमा',
        'From': 'से',
        'To': 'तक',
        'Clear Dates': 'तिथियां साफ़ करें',
        'Clear Times': 'समय साफ़ करें',
        'System Name': 'सिस्टम का नाम',
        'Organization / Building Name': 'संगठन / भवन का नाम',
        'Timezone': 'समयक्षेत्र',
        'Language': 'भाषा',
        'Locker Management': 'लॉकर प्रबंधन',
        'Install New Locker': 'नया लॉकर स्थापित करें',
        'Loading Dashboard...': 'डैशबोर्ड लोड हो रहा है...',
        'Confirm Action': 'कार्रवाई की पुष्टि करें',
        'Confirm Override': 'ओवरराइड की पुष्टि करें',
        'General settings saved!': 'सामान्य सेटिंग्स सहेजी गईं!',
        'Locker configuration saved!': 'लॉकर कॉन्फ़िगरेशन सहेजा गया!',
        'Security settings saved!': 'सुरक्षा सेटिंग्स सहेजी गईं!',
        'Notification settings saved!': 'अधिसूचना सेटिंग्स सहेजी गईं!',
        'Hardware settings saved!': 'हार्डवेयर सेटिंग्स सहेजी गईं!',
        'User management settings saved!': 'उपयोगकर्ता प्रबंधन सेटिंग्स सहेजी गईं!',
        'Appearance settings saved!': 'रूप-रंग सेटिंग्स सहेजी गईं!',
        'General': 'सामान्य',
        'Locker Config': 'लॉकर कॉन्फ़िगरेशन',
        'Security': 'सुरक्षा',
        'Notifications': 'अधिसूचनाएं',
        'Hardware': 'हार्डवेयर',
        'User Mgmt': 'उपयोगकर्ता प्रबंधन',
        'Appearance': 'रूप-रंग',
        'Locker Configuration': 'लॉकर कॉन्फ़िगरेशन',
        'Auto Lock Delay (seconds)': 'ऑटो लॉक देरी (सेकंड)',
        'Unlock Duration (seconds)': 'अनलॉक अवधि (सेकंड)',
        'Door Open Timeout (seconds)': 'दरवाजा खुला टाइमआउट (सेकंड)',
        'Enable Auto-lock': 'ऑटो-लॉक सक्षम करें',
        'Automatically lock the door after the delay period': 'देरी की अवधि के बाद दरवाजा अपने आप लॉक करें',
        'Security Settings': 'सुरक्षा सेटिंग्स',
        'OTP Expiry Time (minutes)': 'ओटीपी समाप्ति समय (मिनट)',
        'Maximum Failed Attempts': 'अधिकतम विफल प्रयास',
        'Session Timeout (minutes)': 'सत्र टाइमआउट (मिनट)',
        'Enable Two Factor Authentication': 'द्वि-कारक प्रमाणीकरण सक्षम करें',
        'Require an extra code for administrative logins': 'प्रशासनिक लॉगिन के लिए एक अतिरिक्त कोड की आवश्यकता है',
        'Notification Settings': 'अधिसूचना सेटिंग्स',
        'Email Notifications': 'ईमेल अधिसूचनाएं',
        'Receive system updates via email': 'ईमेल के माध्यम से सिस्टम अपडेट प्राप्त करें',
        'SMS Notifications': 'एसएमएस अधिसूचनाएं',
        'Receive urgent alerts via SMS': 'एसएमएस के माध्यम से तत्काल अलर्ट प्राप्त करें',
        'Door Left Open Alerts': 'दरवाजा खुला रहने का अलर्ट',
        'Notify if a locker door remains open too long': 'यदि लॉकर का दरवाजा बहुत देर तक खुला रहता है तो सूचित करें',
        'Failed Access Alerts': 'विफल एक्सेस अलर्ट',
        'Notify after suspicious failed entry attempts': 'संदिग्ध विफल प्रवेश प्रयासों के बाद सूचित करें',
        'Hardware Settings': 'हार्डवेयर सेटिंग्स',
        'Device Status': 'डिवाइस की स्थिति',
        'Last heartbeat': 'अंतिम हार्टबीट',
        'Device Name': 'डिवाइस का नाम',
        'Device IP Address': 'डिवाइस आईपी पता',
        'Test Connection': 'कनेक्शन का परीक्षण करें',
        'Restart Device': 'डिवाइस पुनरारंभ करें',
        'Simulate System Alert': 'सिस्टम अलर्ट का अनुकरण करें',
        'Connected': 'जुड़ा हुआ है',
        'Testing connection to': 'कनेक्शन का परीक्षण किया जा रहा है',
        'Are you sure you want to restart the hardware controller?': 'क्या आप वाकई हार्डवेयर कंट्रोलर को पुनरारंभ करना चाहते हैं?',
        'Restart command sent.': 'पुनरारंभ कमांड भेजी गई।',
        'System Alert simulated! Check the Events Log.': 'सिस्टम अलर्ट अनुकरणित! ईवेंट्स लॉग जांचें।',
        'User Management Settings': 'उपयोगकर्ता प्रबंधन सेटिंग्स',
        'Allow Resident Self Registration': 'निवासी स्व-पंजीकरण की अनुमति दें',
        'Residents can create their own accounts via the user app': 'निवासी उपयोगकर्ता ऐप के माध्यम से अपना स्वयं का खाता बना सकते हैं',
        'Maximum Lockers per Resident': 'प्रति निवासी अधिकतम लॉकर',
        'Resident Inactivity Timeout (days)': 'निवासी निष्क्रियता टाइमआउट (दिन)',
        'Appearance Settings': 'रूप-रंग सेटिंग्स',
        'Theme': 'थीम',
        'Applied': 'लागू किया गया',
        'Light': 'लाइट',
        'Dark': 'डार्क',
        'Theme is applied instantly — no save required.': 'थीम तुरंत लागू होती है — सहेजने की आवश्यकता नहीं है।',
        'Primary Color': 'प्राथमिक रंग',
        'Organization Logo': 'संगठन का लोगो',
        'Change Logo': 'लोगो बदलें',
        'PNG, JPG or SVG. Max 2MB.': 'पीएनजी, जेपीजी या एसवीजी। अधिकतम 2एमबी।',
        'Description': 'विवरण',
        'Type': 'प्रकार',
        'Locker': 'लॉकर',
        '2 minutes ago': '2 मिनट पहले',
        'Search...': 'खोजें...',
        'Admin User': 'एडमिन उपयोगकर्ता',
        'Super Admin': 'सुपर एडमिन',
        'Super User': 'सुपर उपयोगकर्ता',
        'View All': 'सभी देखें',
        'Loading...': 'लोड हो रहा है...',
        'No recent activity': 'कोई हालकी गतिविधि नहीं',
        'Showing last 10 system events': 'पिछले 10 सिस्टम ईवेंट्स दिखा रहे हैं',
        'No events found.': 'कोई ईवेंट्स नहीं मिले।',
        'DELIVERY': 'डिलिवरी',
        'PICKUP': 'पिकअप',
        'CLOSE': 'बंद करें',
        'ADMIN_OVERRIDE': 'एडमिन ओवरराइड',
        'SYSTEM_ALERT': 'सिस्टम अलर्ट',
        'EVENT': 'ईवेंट',
        'Delivery': 'डिलिवरी',
        'Pickup': 'पिकअप',
        'Verify Email': 'ईमेल सत्यापित करें',
        '6-Digit OTP': '6-अंकीय OTP',
        'Verify & Continue': 'सत्यापित करें और जारी रखें',
        'Update Resident': 'निवासी को अपडेट करें',
        'Complete Registration': 'पंजीकरण पूरा करें',
        'Update Registration': 'पंजीकरण अपडेट करें',
        'Didn\'t get a code? Resend': 'कोड नहीं मिला? पुन: भेजें',
        'No Activity': 'कोई गतिविधि नहीं',
        'Verify Gmail': 'Gmail सत्यापित करें',
        'No residents found.': 'कोई निवासी नहीं मिले।',
        'Admin Override Warning': 'एडमिन ओवरराइड चेतावनी',
        'You are about to manually': 'आप मैन्युअल रूप से करने वाले हैं',
        'locker': 'लॉकर',
        'This action will be logged in the system audit trail.': 'यह क्रिया सिस्टम ऑडिट ट्रेल में लॉग की जाएगी।',
        'force open': 'बलपूर्वक खोलें',
        'reset': 'रीसेट',
        'Must be unique across the system.': 'सिस्टम में अद्वितीय होना चाहिए।',
        'desc_admin_reset': 'लॉकर {lockerId} व्यवस्थापक द्वारा मैन्युअल रूप से रीसेट किया गया',
        'desc_delivery': 'लॉकर {lockerId} में {owner} के लिए नया पैकेज',
        'desc_pickup': 'अपार्टमेंट {apt} के निवासी द्वारा पैकेज एकत्र किया गया',
        'desc_admin_open': 'व्यवस्थापक ओवरराइड द्वारा लॉकर का दरवाजा खोला गया',
        'desc_close': 'लॉकर का दरवाजा बंद और सुरक्षित',
        'desc_alert': 'सिस्टम अलर्ट: यूनिट {lockerId} पर अनियमित गतिविधि का पता चला',
        'No description provided': 'कोई विवरण प्रदान नहीं किया गया',
        'Revenue per Pickup ($)': 'प्रति पिकअप राजस्व ($)',
        'Revenue Settings': 'राजस्व सेटिंग्स',
        'Amount earned per successful package pickup': 'प्रत्येक सफल पैकेज पिकअप पर अर्जित राशि',
        'Download Logo': 'लोगो डाउनलोड करें'
    },
    'Spanish': {
        'Overview': 'Resumen',
        'Lockers': 'Casilleros',
        'Residents': 'Residentes',
        'Events': 'Eventos',
        'Settings': 'Ajustes',
        'Admin Panel': 'Panel de administrador',
        'Logout': 'Cerrar sesión',
        'Total Deliveries': 'Entregas totales',
        'Revenue': 'Ingresos',
        'Efficiency': 'Eficiencia',
        'Issues': 'Problemas',
        'Occupancy Trends': 'Tendencias de ocupación',
        'This Week': 'Esta semana',
        'Last Week': 'Semana pasada',
        'Recent Activity': 'Actividad reciente',
        'Add Unit': 'Añadir unidad',
        'Refresh Status': 'Actualizar estado',
        'Ready for use': 'Listo para usar',
        'Occupied': 'Ocupado',
        'Open': 'Abrir',
        'Reset': 'Reiniciar',
        'Locker ID': 'ID del casillero',
        'Resident Directory': 'Directorio de residentes',
        'Add Resident': 'Añadir residente',
        'User': 'Usuario',
        'Apartment': 'Apartamento',
        'Actions': 'Acciones',
        'Delete': 'Eliminar',
        'Edit': 'Editar',
        'Full Name': 'Nombre completo',
        'Email': 'Correo electrónico',
        'Apartment ID': 'ID del apartamento',
        'Cancel': 'Cancelar',
        'Save Changes': 'Guardar cambios',
        'System Events': 'Eventos del sistema',
        'All Types': 'Todos los tipos',
        'Date Range': 'Rango de fechas',
        'Time Range': 'Rango de tiempo',
        'From': 'Desde',
        'To': 'Hasta',
        'Clear Dates': 'Borrar fechas',
        'Clear Times': 'Borrar horas',
        'System Name': 'Nombre del sistema',
        'Organization / Building Name': 'Nombre de la organización / edificio',
        'Timezone': 'Zona horaria',
        'Language': 'Idioma',
        'Locker Management': 'Gestión de casilleros',
        'Install New Locker': 'Instalar nuevo casillero',
        'Loading Dashboard...': 'Cargando tablero...',
        'Confirm Action': 'Confirmar acción',
        'Confirm Override': 'Confirmar anulación',
        'General settings saved!': '¡Ajustes generales guardados!',
        'Locker configuration saved!': '¡Configuración del casillero guardada!',
        'Security settings saved!': '¡Ajustes de seguridad guardados!',
        'Notification settings saved!': '¡Ajustes de notificación guardados!',
        'Hardware settings saved!': '¡Ajustes de hardware guardados!',
        'User management settings saved!': '¡Ajustes de gestión de usuarios guardados!',
        'Appearance settings saved!': '¡Ajustes de apariencia guardados!',
        'General': 'General',
        'Locker Config': 'Configuración de casilleros',
        'Security': 'Seguridad',
        'Notifications': 'Notificaciones',
        'Hardware': 'Hardware',
        'User Mgmt': 'Gestión de usuarios',
        'Appearance': 'Apariencia',
        'Locker Configuration': 'Configuración de casilleros',
        'Auto Lock Delay (seconds)': 'Retraso de bloqueo automático (segundos)',
        'Unlock Duration (seconds)': 'Duración de desbloqueo (segundos)',
        'Door Open Timeout (seconds)': 'Tiempo de espera de puerta abierta (segundos)',
        'Enable Auto-lock': 'Habilitar bloqueo automático',
        'Automatically lock the door after the delay period': 'Bloquear automáticamente la puerta después del periodo de retraso',
        'Security Settings': 'Ajustes de seguridad',
        'OTP Expiry Time (minutes)': 'Tiempo de expiración de OTP (minutos)',
        'Maximum Failed Attempts': 'Máximo de intentos fallidos',
        'Session Timeout (minutes)': 'Tiempo de espera de la sesión (minutos)',
        'Enable Two Factor Authentication': 'Habilitar autenticación de dos factores',
        'Require an extra code for administrative logins': 'Requerir un código adicional para inicios de sesión administrativos',
        'Notification Settings': 'Ajustes de notificación',
        'Email Notifications': 'Notificaciones por correo electrónico',
        'Receive system updates via email': 'Recibir actualizaciones del sistema por correo electrónico',
        'SMS Notifications': 'Notificaciones por SMS',
        'Receive urgent alerts via SMS': 'Recibir alertas urgentes por SMS',
        'Door Left Open Alerts': 'Alertas de puerta abierta',
        'Notify if a locker door remains open too long': 'Notificar si la puerta de un casillero permanece abierta demasiado tiempo',
        'Failed Access Alerts': 'Alertas de acceso fallido',
        'Notify after suspicious failed entry attempts': 'Notificar después de intentos de entrada fallidos sospechosos',
        'Hardware Settings': 'Ajustes de hardware',
        'Device Status': 'Estado del dispositivo',
        'Last heartbeat': 'Último latido',
        'Device Name': 'Nombre del dispositivo',
        'Device IP Address': 'Dirección IP del dispositivo',
        'Test Connection': 'Probar conexión',
        'Restart Device': 'Reiniciar dispositivo',
        'Simulate System Alert': 'Simular alerta del sistema',
        'Connected': 'Conectado',
        'Testing connection to': 'Probando conexión a',
        'Are you sure you want to restart the hardware controller?': '¿Está seguro de que desea reiniciar el controlador de hardware?',
        'Restart command sent.': 'Comando de reinicio enviado.',
        'System Alert simulated! Check the Events Log.': '¡Alerta del sistema simulada! Revise el registro de eventos.',
        'User Management Settings': 'Ajustes de gestión de usuarios',
        'Allow Resident Self Registration': 'Permitir autoregistro de residentes',
        'Residents can create their own accounts via the user app': 'Los residentes pueden crear sus propias cuentas a través de la aplicación de usuario',
        'Maximum Lockers per Resident': 'Máximo de casilleros por residente',
        'Resident Inactivity Timeout (days)': 'Tiempo de espera por inactividad del residente (días)',
        'Appearance Settings': 'Ajustes de apariencia',
        'Theme': 'Tema',
        'Applied': 'Aplicado',
        'Light': 'Claro',
        'Dark': 'Oscuro',
        'Theme is applied instantly — no save required.': 'El tema se aplica instantáneamente; no es necesario guardar.',
        'Primary Color': 'Color primario',
        'Organization Logo': 'Logo de la organización',
        'Change Logo': 'Cambiar logo',
        'PNG, JPG or SVG. Max 2MB.': 'PNG, JPG o SVG. Máx. 2MB.',
        'Description': 'Descripción',
        'Type': 'Tipo',
        'Locker': 'Casillero',
        '2 minutes ago': 'Hace 2 minutos',
        'Search...': 'Buscar...',
        'Admin User': 'Usuario administrador',
        'Super Admin': 'Superadministrador',
        'Super User': 'Superusuario',
        'View All': 'Ver todo',
        'Loading...': 'Cargando...',
        'No recent activity': 'Sin actividad reciente',
        'Showing last 10 system events': 'Mostrando los últimos 10 eventos del sistema',
        'No events found.': 'No se encontraron eventos.',
        'DELIVERY': 'Entrega',
        'PICKUP': 'Recogida',
        'CLOSE': 'Cerrar',
        'ADMIN_OVERRIDE': 'Anulación de administrador',
        'SYSTEM_ALERT': 'Alerta del sistema',
        'EVENT': 'Evento',
        'Delivery': 'Entrega',
        'Pickup': 'Recogida',
        'Verify Email': 'Verificar correo electrónico',
        '6-Digit OTP': 'OTP de 6 dígitos',
        'Verify & Continue': 'Verificar y continuar',
        'Update Resident': 'Actualizar residente',
        'Complete Registration': 'Completar registro',
        'Update Registration': 'Actualizar registro',
        'Didn\'t get a code? Resend': '¿No recibiste el código? Reenviar',
        'No Activity': 'Sin actividad',
        'Verify Gmail': 'Verificar Gmail',
        'No residents found.': 'No se encontraron residentes.',
        'Admin Override Warning': 'Advertencia de anulación del administrador',
        'You are about to manually': 'Está a punto de realizar manualmente',
        'locker': 'casillero',
        'This action will be logged in the system audit trail.': 'Esta acción se registrará en la pista de auditoría del sistema.',
        'force open': 'forzar apertura',
        'reset': 'reiniciar',
        'Must be unique across the system.': 'Debe ser único en todo el sistema.',
        'desc_admin_reset': 'Locker {lockerId} restablecido manualmente por el administrador',
        'desc_delivery': 'Nuevo paquete para {owner} en el Locker {lockerId}',
        'desc_pickup': 'Paquete recogido por el residente del Apt {apt}',
        'desc_admin_open': 'Puerta del casillero abierta por anulación del administrador',
        'desc_close': 'Puerta del casillero cerrada y asegurada',
        'desc_alert': 'Alerta del sistema: actividad irregular detectada en la unidad {lockerId}',
        'No description provided': 'No se proporcionó descripción',
        'Revenue per Pickup ($)': 'Ingresos por recogida ($)',
        'Revenue Settings': 'Ajustes de ingresos',
        'Amount earned per successful package pickup': 'Cantidad ganada por cada recogida de paquete exitosa',
        'Download Logo': 'Descargar logo'
    },
    'Arabic': {
        'Overview': 'نظرة عامة',
        'Lockers': 'خزائن',
        'Residents': 'سكان',
        'Events': 'أحداث',
        'Settings': 'إعدادات',
        'Admin Panel': 'لوحة الإدارة',
        'Logout': 'تسجيل الخروج',
        'Total Deliveries': 'إجمالي عمليات التسليم',
        'Revenue': 'الإيرادات',
        'Efficiency': 'الكفاءة',
        'Issues': 'مشكلات',
        'Occupancy Trends': 'اتجاهات الإشغال',
        'This Week': 'هذا الأسبوع',
        'Last Week': 'الأسبوع الماضي',
        'Recent Activity': 'النشاط الأخير',
        'Add Unit': 'إضافة وحدة',
        'Refresh Status': 'تحديث الحالة',
        'Ready for use': 'جاهز للاستخدام',
        'Occupied': 'مشغول',
        'Open': 'فتح',
        'Reset': 'إعادة ضبط',
        'Locker ID': 'معرف الخزانة',
        'Resident Directory': 'دليل السكان',
        'Add Resident': 'إضافة ساكن',
        'User': 'مستخدم',
        'Apartment': 'شقة',
        'Actions': 'إجراءات',
        'Delete': 'حذف',
        'Edit': 'تعديل',
        'Full Name': 'الاسم الكامل',
        'Email': 'البريد الإلكتروني',
        'Apartment ID': 'معرف الشقة',
        'Cancel': 'إلغاء',
        'Save Changes': 'حفظ التغييرات',
        'System Events': 'أحداث النظام',
        'All Types': 'جميع الأنواع',
        'Date Range': 'نطاق التاريخ',
        'Time Range': 'نطاق الوقت',
        'From': 'من',
        'To': 'إلى',
        'Clear Dates': 'مسح التواريخ',
        'Clear Times': 'مسح الأوقات',
        'System Name': 'اسم النظام',
        'Organization / Building Name': 'اسم المنظمة / المبنى',
        'Timezone': 'المنطقة الزمنية',
        'Language': 'اللغة',
        'Locker Management': 'إدارة الخزائن',
        'Install New Locker': 'تثبيت خزانة جديدة',
        'Loading Dashboard...': 'جارٍ تحميل لوحة المعلومات...',
        'Confirm Action': 'تأكيد الإجراء',
        'Confirm Override': 'تأكيد التجاوز',
        'General settings saved!': 'تم حفظ الإعدادات العامة!',
        'Locker configuration saved!': 'تم حفظ تكوين الخزانة!',
        'Security settings saved!': 'تم حفظ إعدادات الأمان!',
        'Notification settings saved!': 'تم حفظ إعدادات التنبيهات!',
        'Hardware settings saved!': 'تم حفظ إعدادات الأجهزة!',
        'User management settings saved!': 'تم حفظ إعدادات إدارة المستخدمين!',
        'Appearance settings saved!': 'تم حفظ إعدادات المظهر!',
        'General': 'عام',
        'Locker Config': 'تكوين الخزانة',
        'Security': 'الأمان',
        'Notifications': 'التنبيهات',
        'Hardware': 'الأجهزة',
        'User Mgmt': 'إدارة المستخدمين',
        'Appearance': 'المظهر',
        'Locker Configuration': 'تكوين الخزانة',
        'Auto Lock Delay (seconds)': 'تأخير القفل التلقائي (ثوانٍ)',
        'Unlock Duration (seconds)': 'مدة فتح القفل (ثوانٍ)',
        'Door Open Timeout (seconds)': 'مهلة فتح الباب (ثوانٍ)',
        'Enable Auto-lock': 'تمكين القفل التلقائي',
        'Automatically lock the door after the delay period': 'قفل الباب تلقائيًا بعد فترة التأخير',
        'Security Settings': 'إعدادات الأمان',
        'OTP Expiry Time (minutes)': 'وقت انتهاء صلاحية OTP (دقائق)',
        'Maximum Failed Attempts': 'الحد الأقصى للمحاولات الفاشلة',
        'Session Timeout (minutes)': 'مهلة الجلسة (دقائق)',
        'Enable Two Factor Authentication': 'تمكين المصادقة الثنائية',
        'Require an extra code for administrative logins': 'تطلب رمزًا إضافيًا لتسجيل دخول المسؤولين',
        'Notification Settings': 'إعدادات التنبيهات',
        'Email Notifications': 'تنبيهات البريد الإلكتروني',
        'Receive system updates via email': 'تلقي تحديثات النظام عبر البريد الإلكتروني',
        'SMS Notifications': 'تنبيهات SMS',
        'Receive urgent alerts via SMS': 'تلقي تنبيهات عاجلة عبر SMS',
        'Door Left Open Alerts': 'تنبيهات ترك الباب مفتوحًا',
        'Notify if a locker door remains open too long': 'التنبيه إذا ظل باب الخزانة مفتوحًا لفترة طويلة',
        'Failed Access Alerts': 'تنبيهات فشل الوصول',
        'Notify after suspicious failed entry attempts': 'التنبيه بعد محاولات دخول فاشلة مشبوهة',
        'Hardware Settings': 'إعدادات الأجهزة',
        'Device Status': 'حالة الجهاز',
        'Last heartbeat': 'آخر نبضات القلب',
        'Device Name': 'اسم الجهاز',
        'Device IP Address': 'عنوان IP للجهاز',
        'Test Connection': 'اختبار الاتصال',
        'Restart Device': 'إعادة تشغيل الجهاز',
        'Simulate System Alert': 'محاكاة تنبيه النظام',
        'Connected': 'متصل',
        'Testing connection to': 'اختبار الاتصال بـ',
        'Are you sure you want to restart the hardware controller?': 'هل أنت متأكد من رغبتك في إعادة تشغيل متحكم الأجهزة؟',
        'Restart command sent.': 'تم إرسال أمر إعادة التشغيل.',
        'System Alert simulated! Check the Events Log.': 'تمت محاكاة تنبيه النظام! تحقق من سجل الأحداث.',
        'User Management Settings': 'إعدادات إدارة المستخدمين',
        'Allow Resident Self Registration': 'السماح بالتسجيل الذاتي للسكان',
        'Residents can create their own accounts via the user app': 'يمكن للسكان إنشاء حساباتهم الخاصة عبر تطبيق المستخدم',
        'Maximum Lockers per Resident': 'الحد الأقصى للخزائن لكل ساكن',
        'Resident Inactivity Timeout (days)': 'مهلة خمول الساكن (أيام)',
        'Appearance Settings': 'إعدادات المظهر',
        'Theme': 'المظهر',
        'Applied': 'تم التطبيق',
        'Light': 'فاتح',
        'Dark': 'داكن',
        'Theme is applied instantly — no save required.': 'يتم تطبيق المظهر فوراً - لا حاجة للحفظ.',
        'Primary Color': 'اللون الأساسي',
        'Organization Logo': 'شعار المنظمة',
        'Change Logo': 'تغيير الشعار',
        'PNG, JPG or SVG. Max 2MB.': 'PNG، JPG أو SVG. بحد أقصى 2 ميجابايت.',
        'Description': 'الوصف',
        'Type': 'النوع',
        'Locker': 'خزانة',
        '2 minutes ago': 'منذ دقيقتين',
        'Search...': 'بحث...',
        'Admin User': 'مستخدم مسؤول',
        'Super Admin': 'مسؤول فائق',
        'Super User': 'مستخدم فائق',
        'View All': 'عرض الكل',
        'Loading...': 'جارٍ التحميل...',
        'No recent activity': 'لا يوجد نشاط أخير',
        'Showing last 10 system events': 'عرض آخر 10 أحداث للنظام',
        'No events found.': 'لم يتم العثور على أحداث.',
        'DELIVERY': 'تسليم',
        'PICKUP': 'استلام',
        'CLOSE': 'إغلاق',
        'ADMIN_OVERRIDE': 'تجاوز المسؤول',
        'SYSTEM_ALERT': 'تنبيه النظام',
        'EVENT': 'حدث',
        'Delivery': 'تسليم',
        'Pickup': 'استلام',
        'Verify Email': 'التحقق من البريد الإلكتروني',
        '6-Digit OTP': 'رمز OTP من 6 أرقام',
        'Verify & Continue': 'التحقق والمتابعة',
        'Update Resident': 'تحديث الساكن',
        'Complete Registration': 'إكمال التسجيل',
        'Update Registration': 'تحديث التسجيل',
        'Didn\'t get a code? Resend': 'لم يصلك الرمز؟ إعادة الإرسال',
        'No Activity': 'لا يوجد نشاط',
        'Verify Gmail': 'التحقق من Gmail',
        'No residents found.': 'لم يتم العثور على سكان.',
        'Admin Override Warning': 'تحذير تجاوز المسؤول',
        'You are about to manually': 'أنت على وشك القيام يدويًا بـ',
        'locker': 'الخزانة',
        'This action will be logged in the system audit trail.': 'سيتم تسجيل هذا الإجراء في سجل تدقيق النظام.',
        'force open': 'فرض الفتح',
        'reset': 'إعادة ضبط',
        'Must be unique across the system.': 'يجب أن يكون فريداً عبر النظام.',
        'desc_admin_reset': 'تمت إعادة ضبط الخزانة {lockerId} يدويًا بواسطة المسؤول',
        'desc_delivery': 'طرد جديد لـ {owner} في الخزانة {lockerId}',
        'desc_pickup': 'تم استلام الطرد من قبل ساكن الشقة {apt}',
        'desc_admin_open': 'تم فتح باب الخزانة عن طريق تجاوز المسؤول',
        'desc_close': 'باب الخزانة مغلق ومؤمن',
        'desc_alert': 'تنبيه النظام: تم اكتشاف نشاط غير عادي في الوحدة {lockerId}',
        'No description provided': 'لم يتم تقديم وصف',
        'Revenue per Pickup ($)': 'الإيرادات لكل استلام ($)',
        'Revenue Settings': 'إعدادات الإيرادات',
        'Amount earned per successful package pickup': 'المبلغ المكتسب لكل عملية استلام طرد ناجحة'
    },
    'French': {
        'Overview': 'Aperçu',
        'Lockers': 'Casiers',
        'Residents': 'Résidents',
        'Events': 'Événements',
        'Settings': 'Paramètres',
        'Admin Panel': 'Panneau d\'administration',
        'Logout': 'Déconnexion',
        'Total Deliveries': 'Livraisons totales',
        'Revenue': 'Revenu',
        'Efficiency': 'Efficacité',
        'Issues': 'Problèmes',
        'Occupancy Trends': 'Tendances d\'occupation',
        'This Week': 'Cette semaine',
        'Last Week': 'La semaine dernière',
        'Recent Activity': 'Activité récente',
        'Add Unit': 'Ajouter une unité',
        'Refresh Status': 'Actualiser le statut',
        'Ready for use': 'Prêt à l\'emploi',
        'Occupied': 'Occupé',
        'Open': 'Ouvrir',
        'Reset': 'Réinitialiser',
        'Locker ID': 'ID du casier',
        'Resident Directory': 'Répertoire des résidents',
        'Add Resident': 'Ajouter un résident',
        'User': 'Utilisateur',
        'Apartment': 'Appartement',
        'Actions': 'Actions',
        'Delete': 'Supprimer',
        'Edit': 'Modifier',
        'Full Name': 'Nom complet',
        'Email': 'E-mail',
        'Apartment ID': 'ID de l\'appartement',
        'Cancel': 'Annuler',
        'Save Changes': 'Enregistrer les modifications',
        'System Events': 'Événements système',
        'All Types': 'Tous les types',
        'Date Range': 'Plage de dates',
        'Time Range': 'Plage horaire',
        'From': 'De',
        'To': 'À',
        'Clear Dates': 'Effacer les dates',
        'Clear Times': 'Effacer les heures',
        'System Name': 'Nom du système',
        'Organization / Building Name': 'Nom de l\'organisation / du bâtiment',
        'Timezone': 'Fuseau horaire',
        'Language': 'Langue',
        'Locker Management': 'Gestion des casiers',
        'Install New Locker': 'Installer un nouveau casier',
        'Loading Dashboard...': 'Chargement du tableau de bord...',
        'Confirm Action': 'Confirmer l\'action',
        'Confirm Override': 'Confirmer l\'annulation',
        'General settings saved!': 'Paramètres généraux enregistrés !',
        'Locker configuration saved!': 'Configuration du casier enregistrée !',
        'Security settings saved!': 'Paramètres de sécurité enregistrés !',
        'Notification settings saved!': 'Paramètres de notification enregistrés !',
        'Hardware settings saved!': 'Paramètres matériels enregistrés !',
        'User management settings saved!': 'Paramètres de gestion des utilisateurs enregistrés !',
        'Appearance settings saved!': 'Paramètres d\'apparence enregistrés !',
        'General': 'Général',
        'Locker Config': 'Config casier',
        'Security': 'Sécurité',
        'Notifications': 'Notifications',
        'Hardware': 'Matériel',
        'User Mgmt': 'Gestion utilisateurs',
        'Appearance': 'Apparence',
        'Locker Configuration': 'Configuration des casiers',
        'Auto Lock Delay (seconds)': 'Délai de verrouillage automatique (secondes)',
        'Unlock Duration (seconds)': 'Durée de déverrouillage (secondes)',
        'Door Open Timeout (seconds)': 'Délai de porte ouverte (secondes)',
        'Enable Auto-lock': 'Activer le verrouillage automatique',
        'Automatically lock the door after the delay period': 'Verrouiller automatiquement la porte après le délai',
        'Security Settings': 'Paramètres de sécurité',
        'OTP Expiry Time (minutes)': 'Délai d\'expiration de l\'OTP (minutes)',
        'Maximum Failed Attempts': 'Nombre maximal de tentatives échouées',
        'Session Timeout (minutes)': 'Délai d\'expiration de la session (minutes)',
        'Enable Two Factor Authentication': 'Activer l\'authentification à deux facteurs',
        'Require an extra code for administrative logins': 'Exiger un code supplémentaire pour les connexions administratives',
        'Notification Settings': 'Paramètres de notification',
        'Email Notifications': 'Notifications par e-mail',
        'Receive system updates via email': 'Recevoir les mises à jour du système par e-mail',
        'SMS Notifications': 'Notifications par SMS',
        'Receive urgent alerts via SMS': 'Recevoir des alertes urgentes par SMS',
        'Door Left Open Alerts': 'Alertes de porte laissée ouverte',
        'Notify if a locker door remains open too long': 'Notifier si une porte de casier reste ouverte trop longtemps',
        'Failed Access Alerts': 'Alertes d\'accès échoué',
        'Notify after suspicious failed entry attempts': 'Notifier après des tentatives d\'entrée suspectes échouées',
        'Hardware Settings': 'Paramètres matériels',
        'Device Status': 'État de l\'appareil',
        'Last heartbeat': 'Dernier battement de coeur',
        'Device Name': 'Nom de l\'appareil',
        'Device IP Address': 'Adresse IP de l\'appareil',
        'Test Connection': 'Tester la connexion',
        'Restart Device': 'Redémarrer l\'appareil',
        'Simulate System Alert': 'Simuler une alerte système',
        'Connected': 'Connecté',
        'Testing connection to': 'Test de connexion à',
        'Are you sure you want to restart the hardware controller?': 'Êtes-vous sûr de vouloir redémarrer le contrôleur matériel ?',
        'Restart command sent.': 'Commande de redémarrage envoyée.',
        'System Alert simulated! Check the Events Log.': 'Alerte système simulée ! Vérifiez le journal des événements.',
        'User Management Settings': 'Paramètres de gestion des utilisateurs',
        'Allow Resident Self Registration': 'Autoriser l\'auto-enregistrement des résidents',
        'Residents can create their own accounts via the user app': 'Les résidents peuvent créer leurs propres comptes via l\'application utilisateur',
        'Maximum Lockers per Resident': 'Nombre maximal de casiers par résident',
        'Resident Inactivity Timeout (days)': 'Délai d\'inactivité des résidents (jours)',
        'Appearance Settings': 'Paramètres d\'apparence',
        'Theme': 'Thème',
        'Applied': 'Appliqué',
        'Light': 'Clair',
        'Dark': 'Sombre',
        'Theme is applied instantly — aucune sauvegarde requise.': 'Le thème est appliqué instantanément — aucune sauvegarde requise.',
        'Primary Color': 'Couleur primaire',
        'Organization Logo': 'Logo de l\'organisation',
        'Change Logo': 'Changer le logo',
        'PNG, JPG or SVG. Max 2MB.': 'PNG, JPG ou SVG. Max 2 Mo.',
        'Description': 'Description',
        'Type': 'Type',
        'Locker': 'Casier',
        '2 minutes ago': 'Il y a 2 minutes',
        'Search...': 'Chercher...',
        'Admin User': 'Administrateur',
        'Super Admin': 'Super Admin',
        'Super User': 'Super Utilisateur',
        'View All': 'Voir tout',
        'Loading...': 'Chargement...',
        'No recent activity': 'Aucune activité récente',
        'Showing last 10 system events': 'Affichage des 10 derniers événements système',
        'No events found.': 'Aucun événement trouvé.',
        'DELIVERY': 'Livraison',
        'PICKUP': 'Collecte',
        'CLOSE': 'Fermer',
        'ADMIN_OVERRIDE': 'Dérogation administrateur',
        'SYSTEM_ALERT': 'Alerte système',
        'EVENT': 'Événement',
        'Delivery': 'Livraison',
        'Pickup': 'Collecte',
        'Verify Email': 'Vérifier l\'e-mail',
        '6-Digit OTP': 'OTP à 6 chiffres',
        'Verify & Continue': 'Vérifier et continuer',
        'Update Resident': 'Mettre à jour le résident',
        'Complete Registration': 'Compléter l\'inscription',
        'Update Registration': 'Mettre à jour l\'inscription',
        'Didn\'t get a code? Resend': 'Vous n\'avez pas reçu de code ? Renvoyer',
        'No Activity': 'Aucune activité',
        'Verify Gmail': 'Vérifier Gmail',
        'No residents found.': 'Aucun résident trouvé.',
        'Admin Override Warning': 'Avertissement de dérogation administrateur',
        'You are about to manually': 'Vous êtes sur le point de manuellement',
        'locker': 'casier',
        'This action will be logged in the system audit trail.': 'Cette action sera enregistrée dans la piste d\'audit du système.',
        'force open': 'forcer l\'ouverture',
        'reset': 'réinitialiser',
        'Must be unique across the system.': 'Doit être unique dans tout le système.',
        'desc_admin_reset': 'Casier {lockerId} réinitialisé manuellement par l\'administrateur',
        'desc_delivery': 'Nouveau colis pour {owner} dans le casier {lockerId}',
        'desc_pickup': 'Colis récupéré par le résident de l\'Appartement {apt}',
        'desc_admin_open': 'Porte du casier ouverte par dérogation de l\'administrateur',
        'desc_close': 'Porte du casier fermée et sécurisée',
        'desc_alert': 'Alerte système : activité irrégulière détectée sur l\'unité {lockerId}',
        'No description provided': 'Aucune description fournie',
        'Revenue per Pickup ($)': 'Revenu par collecte ($)',
        'Revenue Settings': 'Paramètres de revenus',
        'Amount earned per successful package pickup': 'Montant gagné pour chaque collecte de colis réussie',
        'Download Logo': 'Télécharger le logo'
    }
};

export const SettingsProvider = ({ children }) => {
    const [settings, setSettings] = useState(() => {
        const saved = localStorage.getItem('smartlock_settings');
        return saved ? JSON.parse(saved) : {
            systemName: 'SmartLock Pro',
            language: 'English (US)',
            revenuePerPickup: 5.50,
            customLogo: null
        };
    });

    useEffect(() => {
        localStorage.setItem('smartlock_settings', JSON.stringify(settings));
        // Update document title
        document.title = settings.systemName;
    }, [settings]);

    const translateDescription = (description) => {
        if (!description) return t('No description provided');

        // Pattern 1: New package for {owner} in Locker {lockerId}
        let match = description.match(/New package for (.*) in Locker (.*)/i);
        if (match) {
            return t('desc_delivery', { owner: match[1], lockerId: match[2] });
        }

        // Pattern 2: Package collected by resident of Apt {apt}
        match = description.match(/Package collected by resident of Apt (.*)/i);
        if (match) {
            return t('desc_pickup', { apt: match[1] });
        }

        // Pattern 3: Locker {lockerId} manually reset by administrator
        match = description.match(/Locker (.*) manually reset by administrator/i);
        if (match) {
            return t('desc_admin_reset', { lockerId: match[1] });
        }

        // Pattern 4: System Alert: Irregular activity detected on unit {lockerId}
        match = description.match(/System Alert: Irregular activity detected on unit (.*)/i);
        if (match) {
            return t('desc_alert', { lockerId: match[1] });
        }

        // Static Patterns
        if (description.includes('opened by administrator override')) {
            return t('desc_admin_open');
        }
        if (description.includes('closed and secured')) {
            return t('desc_close');
        }

        return t(description);
    };

    const updateSettings = (newSettings) => {
        setSettings(prev => ({ ...prev, ...newSettings }));
    };

    const t = (key, params = {}) => {
        const lang = settings.language || 'English (US)';
        let text = translations[lang]?.[key] || translations['English (US)']?.[key] || key;
        
        // Handle parameters: replace {key} with value
        Object.keys(params).forEach(paramKey => {
            text = text.replace(new RegExp(`{${paramKey}}`, 'g'), params[paramKey]);
        });
        
        return text;
    };

    return (
        <SettingsContext.Provider value={{ settings, updateSettings, t, translateDescription }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
};
